#!/usr/bin/env node
// ============================================================================
// Verify a database has every critical object the application depends on.
//
//   node scripts/db/verify-schema.js
//
// Exits 0 when all tables and functions exist, 1 listing the missing ones.
// Used by CI after applying supabase/ci/stub_auth.sql + all migrations, and by
// hand after applying migrations to the live Supabase database.
// In addition to the canonical object lists below, the FRONTEND CONTRACT
// (supabase/api-contract.json, generated by scripts/db/gen-contract.js from
// src/api/domains + src) is compared against the database: every RPC and table
// the frontend calls must exist, so a database behind the frontend fails here
// before it can ever reach the parity gate / a published page.
// Configuration is read ONLY from .env: SUPABASE_DB_URL / DATABASE_URL / POSTGRES_URL.
// ============================================================================

import { readFileSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import pg from 'pg';

const __dirname = resolve(fileURLToPath(import.meta.url), '..');
const ROOT = resolve(__dirname, '..', '..');

const EXPECTED_TABLES = [
  'branches', 'warehouses', 'categories', 'products', 'product_units', 'inventory',
  'customers', 'suppliers', 'sales', 'sale_items', 'purchases', 'purchase_items',
  'expenses', 'users', 'audit_log', 'settings', 'branch_settings', 'units', 'stock_transactions',
  'product_components', 'shifts', 'shift_operations', 'roles', 'document_sequences',
  'raw_materials', 'raw_material_inventory', 'raw_material_batches', 'recipes',
  'recipe_items', 'production_orders', 'production_waste', 'inventory_batches',
  'inventory_ledger', 'warehouse_transfers', 'warehouse_transfer_items',
  'chart_of_accounts', 'journal_entries', 'journal_entry_lines', 'account_mappings',
  'customer_payments', 'supplier_payments', 'treasury_accounts', 'treasury_transactions',
  'bank_reconciliations', 'bank_statement_lines', 'dining_areas', 'dining_tables',
  'orders', 'order_items', 'order_kitchen_sends', 'schema_migrations', 'login_as_log',
  'purchase_requests', 'purchase_request_items', 'rfqs', 'rfq_items',
  'supplier_quotations', 'supplier_quotation_items', 'purchase_receipts', 'purchase_receipt_items',
];

const EXPECTED_FUNCTIONS = [
  'is_pos_admin', 'get_branch_id', 'get_user_role', 'set_updated_at',
  'next_document_number', 'create_user', 'seed_opening_balances',
  'process_sale', 'process_purchase', 'process_refund', 'process_expense',
  'adjust_stock', 'receive_payment', 'pay_supplier', 'process_purchase_return',
  '_product_inv_remove_fifo', '_product_inv_add', '_product_inv_move',
  '_raw_remove_fifo', '_raw_add', '_post_journal_entry', 'post_manual_journal',
  'create_production_order', 'complete_production_order', 'cancel_production_order',
  'create_warehouse_transfer', 'approve_warehouse_transfer', 'reject_warehouse_transfer',
  'get_income_statement', 'get_balance_sheet', 'get_trial_balance', 'get_general_ledger',
  'get_journals', 'get_aging_summary', 'get_audit_trail', 'get_treasury_balances',
  'get_cash_flow', 'get_open_invoices', 'get_party_statement', 'resolve_account_key',
  'ensure_chart_of_accounts', 'guard_user_role_changes', 'protect_last_admin',
  'create_order', 'set_order_status', 'set_table_status',
  'send_to_kitchen',
  'login_as_user', 'return_from_login_as', 'record_login_failure', 'record_login_success',
  'create_purchase_request', 'update_purchase_request_status', 'create_rfq', 'update_rfq_status',
  'record_supplier_quotation', 'select_supplier_quotation', 'get_rfq_comparison',
  'create_purchase_order', 'update_purchase_order_status', 'receive_purchase_order',
  'get_purchase_backorders', 'get_purchase_receipts', 'get_supplier_evaluation',
  'get_supplier_price_impact',
];

function loadContract() {
  const file = join(ROOT, 'supabase', 'api-contract.json');
  try {
    const c = JSON.parse(readFileSync(file, 'utf8'));
    return {
      tables: c.tables,
      rpcs: c.rpcs.map((r) => r.name),
    };
  } catch {
    console.error('ERROR: supabase/api-contract.json missing. Run `node scripts/db/gen-contract.js` first.');
    process.exit(1);
  }
}

function loadEnv(filePath) {
  const env = {};
  let raw;
  try {
    raw = readFileSync(filePath, 'utf8');
  } catch {
    return env;
  }
  for (const line of raw.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq <= 0) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) {
      value = value.slice(1, -1);
    }
    if (key) env[key] = value;
  }
  return env;
}

function buildSsl(connectionString) {
  const sslMode = (connectionString.match(/sslmode=([^&\s]+)/) || [])[1];
  if (sslMode && sslMode !== 'disable') return { rejectUnauthorized: false };
  return false;
}

async function main() {
  const env = loadEnv(join(ROOT, '.env'));
  const dbUrl =
    process.env.SUPABASE_DB_URL || process.env.DATABASE_URL || process.env.POSTGRES_URL ||
    env.SUPABASE_DB_URL || env.DATABASE_URL || env.POSTGRES_URL;
  if (!dbUrl) {
    console.error('ERROR: no database URL found. Add SUPABASE_DB_URL (or DATABASE_URL) to .env.');
    process.exit(1);
  }

  const client = new pg.Client({ connectionString: dbUrl, ssl: buildSsl(dbUrl) });
  await client.connect();

  const tableRows = await client.query(
    `SELECT table_name FROM information_schema.tables WHERE table_schema = 'public'`,
  );
  const existingTables = new Set(tableRows.rows.map((r) => r.table_name));

  const fnRows = await client.query(
    `SELECT proname FROM pg_proc WHERE pronamespace = 'public'::regnamespace GROUP BY proname`,
  );
  const existingFns = new Set(fnRows.rows.map((r) => r.proname));

  const missingTables = EXPECTED_TABLES.filter((t) => !existingTables.has(t));
  const missingFns = EXPECTED_FUNCTIONS.filter((f) => !existingFns.has(f));

  // Frontend contract: every RPC/table the frontend calls must exist.
  const contract = loadContract();
  const contractMissingTables = contract.tables.filter((t) => !existingTables.has(t));
  const contractMissingRpcs = contract.rpcs.filter((f) => !existingFns.has(f));

  console.log(`Tables:  ${EXPECTED_TABLES.length} expected, ${EXPECTED_TABLES.length - missingTables.length} present`);
  console.log(`Functions: ${EXPECTED_FUNCTIONS.length} expected, ${EXPECTED_FUNCTIONS.length - missingFns.length} present`);
  console.log(`Contract RPCs: ${contract.rpcs.length} expected, ${contract.rpcs.length - contractMissingRpcs.length} present`);
  console.log(`Contract tables: ${contract.tables.length} expected, ${contract.tables.length - contractMissingTables.length} present`);

  if (missingTables.length) {
    console.error('\nMissing tables:');
    missingTables.forEach((t) => console.error(`  - ${t}`));
  }
  if (missingFns.length) {
    console.error('\nMissing functions:');
    missingFns.forEach((f) => console.error(`  - ${f}`));
  }
  if (contractMissingTables.length) {
    console.error('\nFrontend contract missing tables (database is behind the frontend):');
    contractMissingTables.forEach((t) => console.error(`  - ${t}`));
  }
  if (contractMissingRpcs.length) {
    console.error('\nFrontend contract missing RPCs (database is behind the frontend):');
    contractMissingRpcs.forEach((f) => console.error(`  - ${f}`));
  }

  const version = await client.query('SELECT version()');
  console.log(`\nServer: ${version.rows[0].version.split(',')[0]}`);
  await client.end();

  if (missingTables.length || missingFns.length || contractMissingTables.length || contractMissingRpcs.length) {
    process.exit(1);
  }
  console.log('\nSchema verification passed.');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
