import type { FeatureCategory, RejectionReason } from './subscription.types';

export interface SystemFeatureDef {
  key: string;
  name_ar: string;
  name_en: string;
  description_ar: string;
  description_en: string;
  category: FeatureCategory;
  is_system?: boolean;
}

export const FEATURE_REGISTRY: Record<string, SystemFeatureDef> = {
  pos: {
    key: 'pos',
    name_ar: 'نقطة البيع (POS)',
    name_en: 'Point of Sale (POS)',
    description_ar: 'إصدار الفواتير ونقاط البيع السريعة والطاولات والدليفري',
    description_en: 'Fast sales invoicing, tables and delivery workflows',
    category: 'core',
    is_system: true,
  },
  inventory: {
    key: 'inventory',
    name_ar: 'إدارة المخزون',
    name_en: 'Inventory Management',
    description_ar: 'متابعة الأرصدة والمستودعات والتسويات المخزنية',
    description_en: 'Track stock balances, warehouses and adjustments',
    category: 'inventory',
    is_system: true,
  },
  purchases: {
    key: 'purchases',
    name_ar: 'المشتريات والموردين',
    name_en: 'Purchases & Suppliers',
    description_ar: 'أوامر الشراء وعروض الأسعار والفواتير المباشرة',
    description_en: 'Purchase orders, RFQs, and receiving',
    category: 'trade',
    is_system: true,
  },
  suppliers: {
    key: 'suppliers',
    name_ar: 'سجل الموردين',
    name_en: 'Suppliers Registry',
    description_ar: 'إدارة حسابات وبيانات الموردين',
    description_en: 'Manage supplier profiles and balances',
    category: 'trade',
    is_system: true,
  },
  customers: {
    key: 'customers',
    name_ar: 'سجل العملاء',
    name_en: 'Customers Registry',
    description_ar: 'إدارة حسابات وبيانات العملاء ونقاط الولاء',
    description_en: 'Manage customer accounts and loyalty',
    category: 'trade',
    is_system: true,
  },
  kds: {
    key: 'kds',
    name_ar: 'شاشة المطبخ (KDS)',
    name_en: 'Kitchen Display System (KDS)',
    description_ar: 'نظام عرض وإدارة طلبات المطبخ والمحطات في الوقت الفعلي',
    description_en: 'Real-time kitchen orders routing and display',
    category: 'operations',
  },
  customer_display: {
    key: 'customer_display',
    name_ar: 'شاشة العميل',
    name_en: 'Customer Display',
    description_ar: 'عرض الطلب والأسعار للعميل أثناء عملية البيع',
    description_en: 'Customer-facing order and pricing display',
    category: 'operations',
  },
  tables: {
    key: 'tables',
    name_ar: 'إدارة الطاولات والصالات',
    name_en: 'Tables & Floor Plan',
    description_ar: 'المخطط التفاعلي للطاولات وتوزيع الصالات',
    description_en: 'Interactive floor plan and table seating',
    category: 'operations',
  },
  delivery: {
    key: 'delivery',
    name_ar: 'إدارة الدليفري والسائقين',
    name_en: 'Delivery & Drivers',
    description_ar: 'تتبع طلبات التوصيل وتوزيع الكباتن والسائقين',
    description_en: 'Delivery tracking and driver management',
    category: 'operations',
  },
  manufacturing: {
    key: 'manufacturing',
    name_ar: 'التصنيع والإنتاج',
    name_en: 'Production & Manufacturing',
    description_ar: 'خطوط الإنتاج والتصنيع وتحويل المواد',
    description_en: 'Manufacturing orders and material conversion',
    category: 'inventory',
  },
  recipes: {
    key: 'recipes',
    name_ar: 'الوصفات والتركيبات',
    name_en: 'Recipes & BOM',
    description_ar: 'مكونات المنتجات وخصم المواد الخام تلقائياً',
    description_en: 'Product recipes and automated ingredient deductions',
    category: 'inventory',
  },
  units: {
    key: 'units',
    name_ar: 'وحدات القياس المتعددة',
    name_en: 'Measurement Units',
    description_ar: 'وحدات التحويل القياسية والتجزئة والكرتون',
    description_en: 'Multi-unit conversions and standard inventory units',
    category: 'inventory',
  },
  reports: {
    key: 'reports',
    name_ar: 'التقارير الأساسية',
    name_en: 'Basic Reports',
    description_ar: 'تقارير المبيعات اليومية والأصناف الأكثر طلباً',
    description_en: 'Daily sales, summaries and top-selling items',
    category: 'analytics',
    is_system: true,
  },
  advanced_reports: {
    key: 'advanced_reports',
    name_ar: 'التقارير المتقدمة والتحليلات',
    name_en: 'Advanced Analytics',
    description_ar: 'تقارير الأرباح والخسائر والتحليلات التنفيذية العميقة',
    description_en: 'Profit & Loss, executive trends and forecasting',
    category: 'analytics',
  },
  excel_import: {
    key: 'excel_import',
    name_ar: 'استيراد البيانات من Excel',
    name_en: 'Excel Import',
    description_ar: 'استيراد قوائم المنتجات والعملاء والمخزون من ملفات Excel',
    description_en: 'Import catalog and inventory from Excel',
    category: 'management',
  },
  excel_export: {
    key: 'excel_export',
    name_ar: 'تصدير التقارير إلى Excel/PDF',
    name_en: 'Export Reports (Excel/PDF)',
    description_ar: 'تصدير كافة الكشوفات والتقارير المالية بصيغ Excel و PDF',
    description_en: 'Export data and reports to Excel and PDF formats',
    category: 'management',
  },
  multi_branch: {
    key: 'multi_branch',
    name_ar: 'الفروع المتعددة',
    name_en: 'Multi-Branch Management',
    description_ar: 'إمكانية فتح وإدارة أكثر من فرع تحت نفس المؤسسة',
    description_en: 'Manage multiple branches under one organization',
    category: 'enterprise',
  },
  branch_management: {
    key: 'branch_management',
    name_ar: 'تخصيص الفروع والصلاحيات',
    name_en: 'Branch Customization',
    description_ar: 'تخصيص الصلاحيات والإعدادات لكل فرع',
    description_en: 'Branch-level settings and access policies',
    category: 'enterprise',
  },
  warehouse_management: {
    key: 'warehouse_management',
    name_ar: 'المستودعات المتعددة',
    name_en: 'Multi-Warehouse',
    description_ar: 'إدارة المخازن المتعددة والتحويلات بين المخازن',
    description_en: 'Multiple storage locations and transfers',
    category: 'inventory',
  },
  employees: {
    key: 'employees',
    name_ar: 'الموظفين والمستخدمين',
    name_en: 'Staff & Users',
    description_ar: 'إدارة الحسابات وطواقم العمل',
    description_en: 'Manage user profiles and staff credentials',
    category: 'management',
    is_system: true,
  },
  advanced_permissions: {
    key: 'advanced_permissions',
    name_ar: 'الصلاحيات المتقدمة والـ RBAC',
    name_en: 'Custom Roles & RBAC',
    description_ar: 'صلاحيات مخصصة وتدقيق الأدوار المتقدمة',
    description_en: 'Granular permissions and customized security roles',
    category: 'management',
  },
  shift_management: {
    key: 'shift_management',
    name_ar: 'إدارة الورديات والكاشير',
    name_en: 'Shift Management',
    description_ar: 'فتح وإغلاق الورديات والعجز والزيادة في الخزينة',
    description_en: 'Open/close shifts and cash reconciliation',
    category: 'operations',
    is_system: true,
  },
  accounting: {
    key: 'accounting',
    name_ar: 'النظام المحاسبي المتكامل',
    name_en: 'Complete Accounting Suite',
    description_ar: 'شجرة الحسابات، قيود اليومية، الخزائن والبنوك، وميزان المراجعة',
    description_en: 'Chart of accounts, general ledger, and reconciliation',
    category: 'finance',
  },
  ai_assistant: {
    key: 'ai_assistant',
    name_ar: 'المساعد الذكي (AI Insights)',
    name_en: 'AI Assistant & Forecasts',
    description_ar: 'توليد التقارير الذكية وتوقعات الطلب عبر الذكاء الاصطناعي',
    description_en: 'AI-generated operational insights and demand forecasts',
    category: 'enterprise',
  },
  api_access: {
    key: 'api_access',
    name_ar: 'الربط الخارجي وواجهة API',
    name_en: 'External API Access',
    description_ar: 'الربط مع المنصات الخارجية وتطبيقات التوصيل والـ ERP',
    description_en: 'REST/GraphQL API endpoints for third-party integrations',
    category: 'enterprise',
  },
  audit_logs: {
    key: 'audit_logs',
    name_ar: 'سجل العمليات والتدقيق (Audit Logs)',
    name_en: 'Audit Trail & Logs',
    description_ar: 'تتبع كامل لكافة الحركات والتعديلات وحذف الفواتير',
    description_en: 'Full audit history of all system events',
    category: 'management',
  },
  costing: {
    key: 'costing',
    name_ar: 'حساب التكاليف وهوامش الربح',
    name_en: 'Costing & Profit Margins',
    description_ar: 'حساب تكلفة الوجبات وتغيرات تكاليف المواد الخام',
    description_en: 'Recipe costing, live COGS and profit margin analysis',
    category: 'inventory',
  },
  waste_management: {
    key: 'waste_management',
    name_ar: 'إدارة الهدر والتوالف',
    name_en: 'Waste Center',
    description_ar: 'تسجيل هدر المطبخ والتوالف المخزنية وتحليل الخسائر',
    description_en: 'Record kitchen waste and inventory write-offs',
    category: 'inventory',
  },
  transfers: {
    key: 'transfers',
    name_ar: 'التحويلات المخزنية',
    name_en: 'Stock Transfers',
    description_ar: 'تحويل البضائع والمواد الخام بين الفروع والمستودعات',
    description_en: 'Inter-branch and inter-warehouse stock movements',
    category: 'inventory',
  },
  stock_counts: {
    key: 'stock_counts',
    name_ar: 'الجرد المخزني',
    name_en: 'Stock Audits & Counts',
    description_ar: 'جلسات الجرد الدوري والمفاجئ وتسوية الفروقات',
    description_en: 'Periodic inventory physical counts and adjustments',
    category: 'inventory',
  },
};

export const REJECTION_MESSAGES: Record<RejectionReason, { ar: string; en: string }> = {
  NO_SUBSCRIPTION: {
    ar: 'لا يوجد اشتراك مفعّل لمنشأتك. يرجى اختيار خطة للاشتراك.',
    en: 'No active subscription found for your organization. Please select a plan.',
  },
  SUBSCRIPTION_EXPIRED: {
    ar: 'انتهت فترة اشتراك منشأتك. يرجى تجديد الاشتراك للمتابعة.',
    en: 'Your subscription has expired. Please renew to continue using this feature.',
  },
  SUBSCRIPTION_SUSPENDED: {
    ar: 'تم تعليق حساب المنشأة مؤقتاً. يرجى التواصل مع الإدارة.',
    en: 'Your organization account is suspended. Please contact support.',
  },
  SUBSCRIPTION_CANCELLED: {
    ar: 'تم إلغاء هذا الاشتراك.',
    en: 'This subscription has been cancelled.',
  },
  FEATURE_DISABLED_GLOBALLY: {
    ar: 'هذه الميزة معطلة مؤقتاً في النظام.',
    en: 'This feature is temporarily disabled globally.',
  },
  FEATURE_NOT_INCLUDED_IN_PLAN: {
    ar: 'هذه الميزة غير متاحة في خطتك الحالية. يمكنك الترقية للحصول عليها.',
    en: 'This feature is not included in your current plan. Upgrade to unlock.',
  },
  BRANCH_OVERRIDE_DISABLED: {
    ar: 'تم تعطيل هذه الميزة خصيصاً لهذا الفرع.',
    en: 'This feature has been specifically disabled for this branch.',
  },
  LIMIT_REACHED: {
    ar: 'لقد استنفدت الحد المسموح به لهذه الميزة في خطتك.',
    en: 'You have reached the maximum allowed limit for this feature in your plan.',
  },
  TENANT_SUSPENDED: {
    ar: 'تم تعليق المنشأة. لا يمكن استخدام الميزات حالياً.',
    en: 'Organization is suspended. Feature access is locked.',
  },
  ACCOUNT_DISABLED: {
    ar: 'حسابك معطل حالياً.',
    en: 'Your user account is disabled.',
  },
  FEATURE_NOT_FOUND: {
    ar: 'الميزة المطلوبة غير مسجلة في النظام.',
    en: 'Requested feature is not recognized.',
  },
  SUPER_ADMIN: {
    ar: 'مسموح (صلاحيات Super Admin الكاملة).',
    en: 'Allowed (Super Admin platform privileges).',
  },
  PLAN_ENABLED: {
    ar: 'متاح ضمن الخطة الحالية.',
    en: 'Included in your active plan.',
  },
  BRANCH_OVERRIDE_ENABLED: {
    ar: 'متاح بتصريح خاص للفرع.',
    en: 'Allowed via branch override.',
  },
};

export const CATEGORY_LABELS: Record<FeatureCategory, { ar: string; en: string }> = {
  core: { ar: 'الأساسيات ونقاط البيع', en: 'Core & POS' },
  operations: { ar: 'العمليات والتشغيل', en: 'Operations' },
  inventory: { ar: 'المخزون والمستودعات', en: 'Inventory' },
  trade: { ar: 'المشتريات والتجارة', en: 'Purchases & Trade' },
  finance: { ar: 'المحاسبة والمالية', en: 'Accounting & Finance' },
  analytics: { ar: 'التقارير والتحليلات', en: 'Analytics & Reports' },
  enterprise: { ar: 'الفروع والمؤسسات', en: 'Enterprise & Multi-Branch' },
  management: { ar: 'الإدارة والصلاحيات', en: 'Management & Staff' },
};
