import { EntityConfig } from './types';

export const ENTITY_CONFIGS: Record<string, EntityConfig> = {
  products: {
    id: 'products',
    titleAr: 'المنتجات',
    titleEn: 'Products',
    descriptionAr: 'استيراد وتصدير بطاقات الأصناف والأسعار والتصنيفات والباركودات',
    descriptionEn: 'Import and export products, categories, barcoding and standard pricing',
    icon: 'Package',
    requiredPermission: 'inventory.products.manage',
    primaryKeyColumn: 'sku',
    columns: [
      {
        key: 'sku',
        labelAr: 'رمز المنتج (SKU)',
        labelEn: 'SKU',
        type: 'string',
        required: true,
        example: 'BUR-001',
        descriptionAr: 'رمز فريد لكل منتج لمنع التكرار',
        descriptionEn: 'Unique product identifier',
        aliases: ['sku', 'كود_المنتج', 'رمز_المنتج', 'رمز المنتج', 'product_sku', 'code'],
      },
      {
        key: 'barcode',
        labelAr: 'الباركود',
        labelEn: 'Barcode',
        type: 'string',
        required: false,
        example: '628100010001',
        descriptionAr: 'باركود المنتج للقراءة عبر الماسح الضوئي',
        descriptionEn: 'Product barcode for barcode scanners',
        aliases: ['barcode', 'الباركود', 'باركود'],
      },
      {
        key: 'name',
        labelAr: 'اسم المنتج',
        labelEn: 'Product Name',
        type: 'string',
        required: true,
        example: 'برجر لحم كلاسيك',
        descriptionAr: 'اسم المنتج بالعربية',
        descriptionEn: 'Product name in Arabic or default',
        aliases: ['name', 'اسم_المنتج', 'الاسم', 'اسم المنتج', 'product_name', 'title'],
      },
      {
        key: 'name_en',
        labelAr: 'الاسم الإنجليزي',
        labelEn: 'English Name',
        type: 'string',
        required: false,
        example: 'Classic Beef Burger',
        descriptionAr: 'اسم المنتج باللغة الإنجليزية',
        descriptionEn: 'English product name',
        aliases: ['name_en', 'الاسم_الانجليزي', 'الاسم الانجليزي', 'english_name'],
      },
      {
        key: 'category',
        labelAr: 'الفئة / التصنيف',
        labelEn: 'Category',
        type: 'string',
        required: false,
        example: 'البرجر والساندوتشات',
        descriptionAr: 'اسم أو كود الفئة التي ينتمي إليها المنتج',
        descriptionEn: 'Category name or code',
        aliases: ['category', 'الفئة', 'التصنيف', 'قسم', 'category_name', 'category_code'],
      },
      {
        key: 'unit',
        labelAr: 'وحدة القياس',
        labelEn: 'Unit',
        type: 'string',
        required: false,
        example: 'قطعة',
        descriptionAr: 'وحدة القياس مثل: قطعة، وجبة، علبة، كجم',
        descriptionEn: 'Measurement unit e.g. Piece, Meal, Box, Kg',
        aliases: ['unit', 'الوحدة', 'وحدة_القياس', 'وحدة القياس', 'unit_name'],
      },
      {
        key: 'cost',
        labelAr: 'التكلفة التقديرية',
        labelEn: 'Cost',
        type: 'number',
        required: false,
        example: 18.5,
        descriptionAr: 'تكلفة المنتج بالريال السعودي',
        descriptionEn: 'Estimated cost in SAR',
        aliases: ['cost', 'التكلفة', 'سعر_التكلفة', 'سعر التكلفة', 'cost_price', 'purchase_price'],
      },
      {
        key: 'price',
        labelAr: 'سعر البيع',
        labelEn: 'Sale Price',
        type: 'number',
        required: true,
        example: 32.0,
        descriptionAr: 'سعر البيع للجمهور شامل أو غير شامل الضريبة',
        descriptionEn: 'Standard sale price',
        aliases: ['price', 'sale_price', 'السعر', 'سعر_البيع', 'سعر البيع', 'selling_price'],
      },
      {
        key: 'tax_rate',
        labelAr: 'نسبة الضريبة %',
        labelEn: 'Tax Rate %',
        type: 'number',
        required: false,
        example: 15,
        descriptionAr: 'النسبة المئوية لضريبة القيمة المضافة (افتراضياً 15%)',
        descriptionEn: 'VAT tax percentage (default 15%)',
        aliases: ['tax', 'tax_rate', 'الضريبة', 'نسبة_الضريبة', 'نسبة الضريبة', 'vat'],
      },
      {
        key: 'is_active',
        labelAr: 'نشط (نعم/لا)',
        labelEn: 'Active (Yes/No)',
        type: 'boolean',
        required: false,
        example: true,
        descriptionAr: 'حالة المنتج (نعم أو لا أو 1 أو 0)',
        descriptionEn: 'Is product active for POS (Yes/No)',
        aliases: ['active', 'is_active', 'نشط', 'الحالة', 'مفعل'],
      },
    ],
    sampleRows: [
      {
        sku: 'BUR-001',
        barcode: '628100010001',
        name: 'برجر لحم أنجوس كلاسيك',
        name_en: 'Classic Angus Burger',
        category: 'البرجر',
        unit: 'وجبة',
        cost: 16.5,
        price: 34.0,
        tax_rate: 15,
        is_active: true,
      },
      {
        sku: 'BUR-002',
        barcode: '628100010002',
        name: 'برجر دجاج كرسبي سبايسي',
        name_en: 'Spicy Crispy Chicken',
        category: 'البرجر',
        unit: 'وجبة',
        cost: 12.0,
        price: 28.0,
        tax_rate: 15,
        is_active: true,
      },
      {
        sku: 'APP-001',
        barcode: '628100010003',
        name: 'بطاطس مقلية بالبهارات',
        name_en: 'Spiced French Fries',
        category: 'المقبلات',
        unit: 'طبق',
        cost: 4.5,
        price: 12.0,
        tax_rate: 15,
        is_active: true,
      },
      {
        sku: 'DRK-001',
        barcode: '628100010004',
        name: 'مشروب غازي كولا 330 مل',
        name_en: 'Cola Can 330ml',
        category: 'المشروبات',
        unit: 'علبة',
        cost: 2.2,
        price: 5.0,
        tax_rate: 15,
        is_active: true,
      },
    ],
    instructionsAr: [
      'حقل رمز المنتج (SKU) واسم المنتج وسعر البيع حقول إجبارية.',
      'إذا كانت الفئة أو وحدة القياس غير مسجلة مسبقاً، سيقوم النظام بإنشائها تلقائياً أثناء الاستيراد.',
      'يقوم النظام بالتحقق من عدم تكرار الـ SKU أو الباركود داخل الملف أو في قاعدة البيانات.',
    ],
    instructionsEn: [
      'SKU, Product Name, and Sale Price are required fields.',
      'Categories and Units not already existing will be gracefully mapped or auto-created.',
      'Duplicate SKUs and barcodes within the spreadsheet or database will be intercepted.',
    ],
  },

  categories: {
    id: 'categories',
    titleAr: 'الفئات والتصنيفات',
    titleEn: 'Categories',
    descriptionAr: 'استيراد شجرة التصنيفات والأقسام الرئيسية والفرعية',
    descriptionEn: 'Import and export product categories hierarchy',
    icon: 'FolderTree',
    requiredPermission: 'inventory.categories.manage',
    primaryKeyColumn: 'code',
    columns: [
      {
        key: 'code',
        labelAr: 'كود الفئة',
        labelEn: 'Category Code',
        type: 'string',
        required: true,
        example: 'CAT-01',
        descriptionAr: 'رمز مميز للفئة',
        descriptionEn: 'Unique category code',
        aliases: ['code', 'كود_الفئة', 'كود الفئة', 'category_code', 'id'],
      },
      {
        key: 'name',
        labelAr: 'اسم الفئة (عربي)',
        labelEn: 'Category Name (Ar)',
        type: 'string',
        required: true,
        example: 'الوجبات السريعة',
        descriptionAr: 'اسم الفئة باللغة العربية',
        descriptionEn: 'Category name in Arabic',
        aliases: ['name', 'اسم_الفئة', 'اسم الفئة', 'category_name', 'name_ar'],
      },
      {
        key: 'name_en',
        labelAr: 'اسم الفئة (إنجليزي)',
        labelEn: 'Category Name (En)',
        type: 'string',
        required: false,
        example: 'Fast Food',
        descriptionAr: 'اسم الفئة باللغة الإنجليزية',
        descriptionEn: 'Category name in English',
        aliases: ['name_en', 'الاسم_الانجليزي', 'english_name'],
      },
      {
        key: 'parent_code',
        labelAr: 'الفئة الرئيسية (الأب)',
        labelEn: 'Parent Category',
        type: 'string',
        required: false,
        example: 'FOOD-MAIN',
        descriptionAr: 'كود أو اسم الفئة الرئيسية إذا كانت فئة فرعية',
        descriptionEn: 'Parent category code or name',
        aliases: ['parent', 'parent_code', 'الفئة_الرئيسية', 'الفئة الرئيسية', 'parent_category'],
      },
      {
        key: 'is_active',
        labelAr: 'نشط (نعم/لا)',
        labelEn: 'Active',
        type: 'boolean',
        required: false,
        example: true,
        descriptionAr: 'حالة تفعيل الفئة',
        descriptionEn: 'Active status',
        aliases: ['active', 'is_active', 'نشط', 'مفعل'],
      },
    ],
    sampleRows: [
      { code: 'CAT-BUR', name: 'البرجر والساندوتشات', name_en: 'Burgers & Sandwiches', parent_code: '', is_active: true },
      { code: 'CAT-APP', name: 'المقبلات والوجبات الجانبية', name_en: 'Appetizers & Sides', parent_code: '', is_active: true },
      { code: 'CAT-DRK', name: 'المشروبات الباردة والساخنة', name_en: 'Beverages', parent_code: '', is_active: true },
    ],
    instructionsAr: ['تأكد من عدم تكرار كود الفئة.', 'إذا كانت الفئة الرئيسية مخصصة، تأكد من إدراجها قبل الفئات الفرعية.'],
    instructionsEn: ['Ensure category codes are unique.', 'Include parent categories before their children.'],
  },

  components: {
    id: 'components',
    titleAr: 'المواد الخام والمكونات',
    titleEn: 'Raw Materials & Components',
    descriptionAr: 'استيراد وتصدير المواد الخام والمستودعات ووحدات القياس وتكاليف الشراء',
    descriptionEn: 'Import raw materials, ingredients, purchase costs and inventory units',
    icon: 'Layers',
    requiredPermission: 'manufacturing.view',
    primaryKeyColumn: 'sku',
    columns: [
      {
        key: 'sku',
        labelAr: 'كود المكون (Component SKU)',
        labelEn: 'Component SKU',
        type: 'string',
        required: true,
        example: 'RM-001',
        descriptionAr: 'رمز المادة الخام الفريد',
        descriptionEn: 'Unique raw material SKU',
        aliases: ['sku', 'كود_المكون', 'كود المكون', 'رمز_المادة', 'material_sku', 'code'],
      },
      {
        key: 'name',
        labelAr: 'اسم المكون / المادة الخام',
        labelEn: 'Component Name',
        type: 'string',
        required: true,
        example: 'لحم أنجوس مفروم',
        descriptionAr: 'الاسم بالعربية',
        descriptionEn: 'Material name',
        aliases: ['name', 'اسم_المكون', 'اسم المكون', 'المادة', 'material_name'],
      },
      {
        key: 'category',
        labelAr: 'تصنيف المادة',
        labelEn: 'Category',
        type: 'string',
        required: false,
        example: 'اللحوم والدواجن',
        descriptionAr: 'قسم المواد الخام',
        descriptionEn: 'Material category',
        aliases: ['category', 'الفئة', 'التصنيف', 'القسم'],
      },
      {
        key: 'unit',
        labelAr: 'وحدة القياس الأساسية',
        labelEn: 'Unit',
        type: 'string',
        required: true,
        example: 'كجم',
        descriptionAr: 'الوحدة المستخدمة في الجرد والوصفات (كجم، جم، لتر، مل، قطعة)',
        descriptionEn: 'Base measurement unit (Kg, g, L, mL, Pc)',
        aliases: ['unit', 'الوحدة', 'وحدة_القياس', 'وحدة القياس', 'unit_name'],
      },
      {
        key: 'cost',
        labelAr: 'سعر تكلفة الوحدة',
        labelEn: 'Cost',
        type: 'number',
        required: false,
        example: 45.0,
        descriptionAr: 'سعر الشراء للوحدة بالريال',
        descriptionEn: 'Unit cost in SAR',
        aliases: ['cost', 'التكلفة', 'سعر_التكلفة', 'سعر التكلفة', 'cost_price'],
      },
      {
        key: 'min_stock',
        labelAr: 'حد الطلب الأدنى',
        labelEn: 'Min Stock Level',
        type: 'number',
        required: false,
        example: 10,
        descriptionAr: 'التنبيه عند وصول الرصيد لهذا الحد',
        descriptionEn: 'Reorder point threshold',
        aliases: ['min_stock', 'الحد_الادنى', 'حد الطلب', 'حد_الطلب', 'reorder_level'],
      },
      {
        key: 'is_active',
        labelAr: 'نشط',
        labelEn: 'Active',
        type: 'boolean',
        required: false,
        example: true,
        descriptionAr: 'حالة المادة الخام',
        descriptionEn: 'Is active',
        aliases: ['active', 'is_active', 'نشط'],
      },
    ],
    sampleRows: [
      { sku: 'RM-BEEF', name: 'لحم أنجوس مفروم طازج', category: 'اللحوم', unit: 'كجم', cost: 42.0, min_stock: 25, is_active: true },
      { sku: 'RM-BUN', name: 'خبز برجر بريوش سمسم', category: 'المخبوزات', unit: 'قطعة', cost: 1.2, min_stock: 100, is_active: true },
      { sku: 'RM-CHEE', name: 'جبنة شيدر شرائح فاخرة', category: 'الألبان', unit: 'شريحة', cost: 0.75, min_stock: 200, is_active: true },
      { sku: 'RM-SAUC', name: 'صوص البرجر الخاص (سري)', category: 'الصلصات', unit: 'كجم', cost: 24.0, min_stock: 15, is_active: true },
    ],
    instructionsAr: [
      'حقل كود المكون (SKU) والاسم ووحدة القياس إلزامية.',
      'سيتم ربط المكونات تلقائياً في شاشات الإنتاج والوصفات والجرد.',
    ],
    instructionsEn: ['SKU, Name, and Unit are mandatory.', 'Components connect to Recipes, Production and Inventory.'],
  },

  recipes: {
    id: 'recipes',
    titleAr: 'الوصفات ومكونات المنتجات (BOM)',
    titleEn: 'Recipes & Product Components',
    descriptionAr: 'استيراد وتحديث وصفات التصنيع بنظام الصف لكل مكون (One Row Per Component)',
    descriptionEn: 'Import Bill of Materials & Recipes using One-Row-Per-Component pattern',
    icon: 'UtensilsCrossed',
    requiredPermission: 'manufacturing.view',
    primaryKeyColumn: 'product_sku',
    columns: [
      {
        key: 'product_sku',
        labelAr: 'كود المنتج التام (Product SKU)',
        labelEn: 'Product SKU',
        type: 'string',
        required: true,
        example: 'BUR-001',
        descriptionAr: 'رمز المنتج المباع الذي تُصنع منه الوصفة (هو الأساس في التجميع)',
        descriptionEn: 'The sellable product SKU to attach this component to',
        aliases: ['product_sku', 'كود_المنتج', 'كود المنتج', 'رمز_المنتج', 'رمز المنتج', 'sku'],
      },
      {
        key: 'product_name',
        labelAr: 'اسم المنتج (للعرض فقط)',
        labelEn: 'Product Name (Display)',
        type: 'string',
        required: false,
        example: 'برجر لحم كلاسيك',
        descriptionAr: 'اسم المنتج للمراجعة البصرية (يُكرر في كل صف للمنتج)',
        descriptionEn: 'Product display name for visual reference',
        aliases: ['product_name', 'اسم_المنتج', 'اسم المنتج', 'name'],
      },
      {
        key: 'component_sku',
        labelAr: 'كود المكون / المادة الخام',
        labelEn: 'Component SKU',
        type: 'string',
        required: true,
        example: 'RM-BEEF',
        descriptionAr: 'كود المادة الخام أو الصنف نصف المصنع الداخل في الوصفة',
        descriptionEn: 'Raw material or component SKU',
        aliases: ['component_sku', 'كود_المكون', 'كود المكون', 'رمز_المادة الخام', 'material_sku'],
      },
      {
        key: 'component_name',
        labelAr: 'اسم المكون (للعرض فقط)',
        labelEn: 'Component Name (Display)',
        type: 'string',
        required: false,
        example: 'لحم أنجوس مفروم',
        descriptionAr: 'اسم المادة الخام للعرض والتأكد',
        descriptionEn: 'Material display name',
        aliases: ['component_name', 'اسم_المكون', 'اسم المكون', 'المادة'],
      },
      {
        key: 'quantity',
        labelAr: 'الكمية المطلوبة للوحدة',
        labelEn: 'Quantity',
        type: 'number',
        required: true,
        example: 0.15,
        descriptionAr: 'كمية المكون المستهلكة لإنتاج حبة واحدة من المنتج',
        descriptionEn: 'Required quantity per single produced unit',
        aliases: ['quantity', 'الكمية', 'كمية_المكون', 'كمية المكون', 'qty'],
      },
      {
        key: 'unit',
        labelAr: 'وحدة الاستهلاك',
        labelEn: 'Unit',
        type: 'string',
        required: false,
        example: 'كجم',
        descriptionAr: 'الوحدة (مثل: كجم، جم، قطعة، مل، لتر)',
        descriptionEn: 'Consumption measurement unit',
        aliases: ['unit', 'الوحدة', 'وحدة_الاستهلاك', 'وحدة الاستهلاك'],
      },
    ],
    sampleRows: [
      { product_sku: 'BUR-001', product_name: 'برجر لحم أنجوس كلاسيك', component_sku: 'RM-BEEF', component_name: 'لحم أنجوس مفروم', quantity: 0.15, unit: 'كجم' },
      { product_sku: 'BUR-001', product_name: 'برجر لحم أنجوس كلاسيك', component_sku: 'RM-BUN', component_name: 'خبز برجر بريوش', quantity: 1, unit: 'قطعة' },
      { product_sku: 'BUR-001', product_name: 'برجر لحم أنجوس كلاسيك', component_sku: 'RM-CHEE', component_name: 'جبنة شيدر شرائح', quantity: 1, unit: 'شريحة' },
      { product_sku: 'BUR-001', product_name: 'برجر لحم أنجوس كلاسيك', component_sku: 'RM-SAUC', component_name: 'صوص البرجر الخاص', quantity: 0.03, unit: 'كجم' },
      { product_sku: 'BUR-002', product_name: 'برجر دجاج كرسبي', component_sku: 'RM-BUN', component_name: 'خبز برجر بريوش', quantity: 1, unit: 'قطعة' },
      { product_sku: 'BUR-002', product_name: 'برجر دجاج كرسبي', component_sku: 'RM-CHEE', component_name: 'جبنة شيدر شرائح', quantity: 1, unit: 'شريحة' },
      { product_sku: 'BUR-002', product_name: 'برجر دجاج كرسبي', component_sku: 'RM-SAUC', component_name: 'صوص البرجر الخاص', quantity: 0.03, unit: 'كجم' },
    ],
    instructionsAr: [
      'نموذج الصف الواحد لكل مكون (One Row Per Component): كرر سطر المنتج لكل مكون من مكوناته.',
      'تكرار اسم وكود المنتج أمر طبيعي ومطلوب، وسيتم تجميعه تلقائياً في وصفة واحدة.',
      'يجب أن تكون الكمية أكبر من الصفر.',
      'سيتم التحقق الصارم من وجود كود المنتج وكود المادة الخام قبل التطبيق.',
    ],
    instructionsEn: [
      'One Row Per Component model: Repeat product row for each required ingredient.',
      'Product repetitions are grouped into a single unified BOM recipe.',
      'Quantities must be strictly greater than zero.',
      'All product SKUs and raw material SKUs will be verified against inventory master data.',
    ],
  },

  prices: {
    id: 'prices',
    titleAr: 'قوائم الأسعار والفروع',
    titleEn: 'Price Lists & Branch Pricing',
    descriptionAr: 'استيراد وتحديث أسعار الأصناف المخصصة للفروع أو قوائم الأسعار الموسمية',
    descriptionEn: 'Import branch-specific prices and promotional price lists',
    icon: 'BadgePercent',
    requiredPermission: 'inventory.products.manage',
    primaryKeyColumn: 'sku',
    columns: [
      {
        key: 'sku',
        labelAr: 'كود المنتج (SKU)',
        labelEn: 'Product SKU',
        type: 'string',
        required: true,
        example: 'BUR-001',
        descriptionAr: 'رمز المنتج المطلوب تعديل سعره',
        descriptionEn: 'Target product SKU',
        aliases: ['sku', 'كود_المنتج', 'product_sku', 'رمز_المنتج'],
      },
      {
        key: 'branch',
        labelAr: 'اسم أو كود الفرع',
        labelEn: 'Branch',
        type: 'string',
        required: false,
        example: 'الفرع الرئيسي',
        descriptionAr: 'الفرع المطبق عليه السعر (فقط للفروع المصرح للمستخدم بها)',
        descriptionEn: 'Target branch authorized for the active user',
        aliases: ['branch', 'الفرع', 'اسم_الفرع', 'كود_الفرع', 'branch_name', 'branch_code'],
      },
      {
        key: 'price_list',
        labelAr: 'اسم قائمة الأسعار',
        labelEn: 'Price List',
        type: 'string',
        required: false,
        example: 'أسعار التوصيل والمنصات',
        descriptionAr: 'اسم القائمة (مثل: عادي، تطبيقات التوصيل، VIP)',
        descriptionEn: 'Price list title (Standard, Delivery apps, VIP)',
        aliases: ['price_list', 'قائمة_الاسعار', 'قائمة الاسعار', 'list_name'],
      },
      {
        key: 'sale_price',
        labelAr: 'سعر البيع الجديد',
        labelEn: 'Sale Price',
        type: 'number',
        required: true,
        example: 38.0,
        descriptionAr: 'سعر البيع الجديد بالريال السعودي',
        descriptionEn: 'New sale price in SAR',
        aliases: ['sale_price', 'price', 'السعر', 'سعر_البيع', 'سعر البيع', 'new_price'],
      },
      {
        key: 'start_date',
        labelAr: 'تاريخ البداية',
        labelEn: 'Start Date',
        type: 'date',
        required: false,
        example: '2026-09-01',
        descriptionAr: 'تاريخ بدء سريان السعر',
        descriptionEn: 'Effective start date (YYYY-MM-DD)',
        aliases: ['start_date', 'تاريخ_البداية', 'تاريخ البداية', 'from_date'],
      },
      {
        key: 'end_date',
        labelAr: 'تاريخ النهاية',
        labelEn: 'End Date',
        type: 'date',
        required: false,
        example: '2026-12-31',
        descriptionAr: 'تاريخ انتهاء السعر (اختياري)',
        descriptionEn: 'Effective end date',
        aliases: ['end_date', 'تاريخ_النهاية', 'تاريخ النهاية', 'to_date'],
      },
      {
        key: 'is_active',
        labelAr: 'نشط',
        labelEn: 'Active',
        type: 'boolean',
        required: false,
        example: true,
        descriptionAr: 'حالة التسعير',
        descriptionEn: 'Active flag',
        aliases: ['active', 'is_active', 'نشط'],
      },
    ],
    sampleRows: [
      { sku: 'BUR-001', branch: 'فرع الرياض العليا', price_list: 'تطبيقات التوصيل', sale_price: 39.0, start_date: '2026-09-01', end_date: '', is_active: true },
      { sku: 'BUR-002', branch: 'فرع الرياض العليا', price_list: 'تطبيقات التوصيل', sale_price: 32.0, start_date: '2026-09-01', end_date: '', is_active: true },
      { sku: 'APP-001', branch: 'فرع جدة التحلية', price_list: 'الصالات', sale_price: 14.0, start_date: '2026-09-01', end_date: '', is_active: true },
    ],
    instructionsAr: [
      'يمنع النظام تعديل أسعار الفروع التي ليس للمستخدم صلاحية عليها (Branch Isolation).',
      'يجب أن يكون سعر البيع رقماً موجباً.',
    ],
    instructionsEn: ['Branch access control is strictly enforced during price imports.', 'Sale prices must be positive numbers.'],
  },

  suppliers: {
    id: 'suppliers',
    titleAr: 'الموردون',
    titleEn: 'Suppliers',
    descriptionAr: 'استيراد وتصدير سجلات الموردين وبيانات التواصل والأرصدة الافتتاحية والضريبة',
    descriptionEn: 'Import vendor records, contact profiles, tax numbers, and payment terms',
    icon: 'Truck',
    requiredPermission: 'parties.suppliers.manage',
    primaryKeyColumn: 'code',
    columns: [
      {
        key: 'code',
        labelAr: 'كود المورد',
        labelEn: 'Supplier Code',
        type: 'string',
        required: true,
        example: 'SUP-001',
        descriptionAr: 'الرمز الفريد للمورد',
        descriptionEn: 'Unique supplier code',
        aliases: ['code', 'كود_المورد', 'كود المورد', 'supplier_code', 'id'],
      },
      {
        key: 'name',
        labelAr: 'اسم المورد / الشركة',
        labelEn: 'Supplier Name',
        type: 'string',
        required: true,
        example: 'شركة التوريدات الغذائية المتقدمة',
        descriptionAr: 'الاسم التجاري للمورد',
        descriptionEn: 'Supplier legal or commercial name',
        aliases: ['name', 'اسم_المورد', 'اسم المورد', 'الشركة', 'supplier_name'],
      },
      {
        key: 'contact_person',
        labelAr: 'الشخص المسؤول',
        labelEn: 'Contact Person',
        type: 'string',
        required: false,
        example: 'أحمد السعيد',
        descriptionAr: 'اسم مسؤول المبيعات',
        descriptionEn: 'Account representative name',
        aliases: ['contact_person', 'المسؤول', 'جهة_الاتصال', 'contact'],
      },
      {
        key: 'phone',
        labelAr: 'رقم الهاتف',
        labelEn: 'Phone Number',
        type: 'string',
        required: false,
        example: '0501234567',
        descriptionAr: 'رقم الجوال أو الهاتف',
        descriptionEn: 'Phone or mobile number',
        aliases: ['phone', 'الهاتف', 'الجوال', 'رقم_الهاتف', 'mobile'],
      },
      {
        key: 'email',
        labelAr: 'البريد الإلكتروني',
        labelEn: 'Email',
        type: 'string',
        required: false,
        example: 'sales@supplies.sa',
        descriptionAr: 'البريد الإلكتروني الرسمي',
        descriptionEn: 'Email address',
        aliases: ['email', 'البريد', 'الايميل', 'البريد_الالكتروني'],
      },
      {
        key: 'tax_number',
        labelAr: 'الرقم الضريبي',
        labelEn: 'Tax Number (VAT)',
        type: 'string',
        required: false,
        example: '300012345600003',
        descriptionAr: 'الرقم الضريبي للمنشأة (15 رقماً في السعودية)',
        descriptionEn: 'VAT registration number',
        aliases: ['tax_number', 'الرقم_الضريبي', 'الرقم الضريبي', 'vat_number'],
      },
      {
        key: 'address',
        labelAr: 'العنوان',
        labelEn: 'Address',
        type: 'string',
        required: false,
        example: 'الرياض - حي السلي - شارع إسطنبول',
        descriptionAr: 'العنوان الجغرافي أو المستودع الرئيسي',
        descriptionEn: 'Physical or warehouse address',
        aliases: ['address', 'العنوان', 'الموقع'],
      },
      {
        key: 'is_active',
        labelAr: 'نشط',
        labelEn: 'Active',
        type: 'boolean',
        required: false,
        example: true,
        descriptionAr: 'حالة المورد',
        descriptionEn: 'Active status',
        aliases: ['active', 'is_active', 'نشط'],
      },
    ],
    sampleRows: [
      { code: 'SUP-001', name: 'شركة المراعي للمنتجات الطازجة', contact_person: 'محمد القحطاني', phone: '0555123456', email: 'sales@almarai.com', tax_number: '300012345600003', address: 'الرياض، الخرج', is_active: true },
      { code: 'SUP-002', name: 'مؤسسة الدقيق والمخابز الذهبية', contact_person: 'سعد المنصور', phone: '0544987654', email: 'orders@goldenbakery.sa', tax_number: '300098765400003', address: 'جدة، المنطقة الصناعية', is_active: true },
    ],
    instructionsAr: ['تأكد من صحة كود المورد وعدم تكراره.', 'الرقم الضريبي يفضل أن يكون 15 رقماً وفق أنظمة هيئة الزكاة والضريبة والجمارك.'],
    instructionsEn: ['Supplier code must be unique.', 'Tax numbers should follow standard 15-digit ZATCA format.'],
  },

  customers: {
    id: 'customers',
    titleAr: 'العملاء والشركات',
    titleEn: 'Customers',
    descriptionAr: 'استيراد وتصدير قاعدة بيانات العملاء وبرامج الولاء والحد الائتماني',
    descriptionEn: 'Import customers, contact details, loyalty points and credit limits',
    icon: 'Users',
    requiredPermission: 'parties.customers.manage',
    primaryKeyColumn: 'code',
    columns: [
      {
        key: 'code',
        labelAr: 'كود العميل',
        labelEn: 'Customer Code',
        type: 'string',
        required: true,
        example: 'CUST-001',
        descriptionAr: 'كود أو رقم العضوية الفريد للعميل',
        descriptionEn: 'Unique customer code or member number',
        aliases: ['code', 'كود_العميل', 'كود العميل', 'customer_code', 'id'],
      },
      {
        key: 'name',
        labelAr: 'اسم العميل / الشركة',
        labelEn: 'Customer Name',
        type: 'string',
        required: true,
        example: 'شركة الرواد للاستثمار',
        descriptionAr: 'اسم العميل أو الجهة',
        descriptionEn: 'Customer or company name',
        aliases: ['name', 'اسم_العميل', 'اسم العميل', 'العميل', 'customer_name'],
      },
      {
        key: 'phone',
        labelAr: 'رقم الجوال',
        labelEn: 'Mobile Number',
        type: 'string',
        required: false,
        example: '0551122334',
        descriptionAr: 'رقم الجوال لتسجيل الدخول والولاء',
        descriptionEn: 'Mobile number for loyalty / lookup',
        aliases: ['phone', 'الجوال', 'الهاتف', 'رقم_الجوال', 'mobile'],
      },
      {
        key: 'email',
        labelAr: 'البريد الإلكتروني',
        labelEn: 'Email',
        type: 'string',
        required: false,
        example: 'finance@alrowad.sa',
        descriptionAr: 'البريد الإلكتروني للفواتير',
        descriptionEn: 'Email for e-invoicing',
        aliases: ['email', 'البريد', 'الايميل'],
      },
      {
        key: 'tax_number',
        labelAr: 'الرقم الضريبي (B2B)',
        labelEn: 'VAT Number (B2B)',
        type: 'string',
        required: false,
        example: '310012345600003',
        descriptionAr: 'الرقم الضريبي إذا كان العميل شركة لإصدار الفاتورة الضريبية',
        descriptionEn: 'Corporate VAT number for B2B tax invoice',
        aliases: ['tax_number', 'الرقم_الضريبي', 'vat_number'],
      },
      {
        key: 'credit_limit',
        labelAr: 'الحد الائتماني',
        labelEn: 'Credit Limit',
        type: 'number',
        required: false,
        example: 10000,
        descriptionAr: 'الحد الأقصى للمبيعات الآجلة بالريال',
        descriptionEn: 'Max credit balance allowed',
        aliases: ['credit_limit', 'الحد_الائتماني', 'الحد الائتماني', 'limit'],
      },
      {
        key: 'is_active',
        labelAr: 'نشط',
        labelEn: 'Active',
        type: 'boolean',
        required: false,
        example: true,
        descriptionAr: 'حالة العميل',
        descriptionEn: 'Active status',
        aliases: ['active', 'is_active', 'نشط'],
      },
    ],
    sampleRows: [
      { code: 'CUST-001', name: 'سلطان بن عبدالعزيز', phone: '0505123456', email: 'sultan@gmail.com', tax_number: '', credit_limit: 0, is_active: true },
      { code: 'CUST-002', name: 'مؤسسة أفق التقنية للتجارة', phone: '0555678901', email: 'accounting@ofooq.sa', tax_number: '310055567800003', credit_limit: 15000, is_active: true },
    ],
    instructionsAr: ['كود العميل واسم العميل حقول إجبارية.', 'الحد الائتماني يفيد في البيع الآجل B2B.'],
    instructionsEn: ['Customer code and name are required.', 'Credit limit applies to B2B credit sales.'],
  },

  purchases: {
    id: 'purchases',
    titleAr: 'فواتير المشتريات (Header + Items)',
    titleEn: 'Purchase Invoices (Header + Items)',
    descriptionAr: 'استيراد فواتير المشتريات مجمعة برقم الفاتورة (Purchase No) مع إضافة المخزون آلياً',
    descriptionEn: 'Import multi-line purchase invoices grouped by Purchase No',
    icon: 'ShoppingCart',
    requiredPermission: 'trade.purchases.create',
    primaryKeyColumn: 'purchase_no',
    columns: [
      {
        key: 'purchase_no',
        labelAr: 'رقم الفاتورة / أمر الشراء',
        labelEn: 'Purchase No',
        type: 'string',
        required: true,
        example: 'PUR-2026-001',
        descriptionAr: 'رقم الفاتورة الذي يجمع كافة أصناف الفاتورة الواحدة في ملف الإكسل',
        descriptionEn: 'Invoice number grouping multiple item lines together',
        aliases: ['purchase_no', 'رقم_الفاتورة', 'رقم الفاتورة', 'رقم_الشراء', 'invoice_no', 'po_number'],
      },
      {
        key: 'date',
        labelAr: 'تاريخ الفاتورة',
        labelEn: 'Invoice Date',
        type: 'date',
        required: true,
        example: '2026-08-29',
        descriptionAr: 'تاريخ تسجيل الفاتورة (YYYY-MM-DD)',
        descriptionEn: 'Invoice recording date',
        aliases: ['date', 'التاريخ', 'تاريخ_الفاتورة', 'تاريخ الفاتورة', 'invoice_date'],
      },
      {
        key: 'supplier_code',
        labelAr: 'كود / اسم المورد',
        labelEn: 'Supplier',
        type: 'string',
        required: true,
        example: 'SUP-001',
        descriptionAr: 'كود أو اسم المورد المسجل في النظام',
        descriptionEn: 'Supplier code or recognized name',
        aliases: ['supplier', 'supplier_code', 'المورد', 'كود_المورد', 'كود المورد'],
      },
      {
        key: 'warehouse',
        labelAr: 'المستودع المستلم',
        labelEn: 'Warehouse',
        type: 'string',
        required: true,
        example: 'مستودع المواد الأولية',
        descriptionAr: 'اسم أو كود المستودع المصرح للمستخدم بإيداع الأصناف به',
        descriptionEn: 'Receiving warehouse name or code (permission checked)',
        aliases: ['warehouse', 'المستودع', 'المخزن', 'warehouse_name', 'warehouse_code'],
      },
      {
        key: 'sku',
        labelAr: 'كود الصنف / المادة الخام (SKU)',
        labelEn: 'Product / Item SKU',
        type: 'string',
        required: true,
        example: 'RM-BEEF',
        descriptionAr: 'رمز الصنف المراد شراؤه',
        descriptionEn: 'Item or material SKU purchased',
        aliases: ['sku', 'كود_الصنف', 'كود الصنف', 'كود_المنتج', 'رمز_المادة', 'product_sku'],
      },
      {
        key: 'quantity',
        labelAr: 'الكمية المشتراة',
        labelEn: 'Quantity',
        type: 'number',
        required: true,
        example: 50.0,
        descriptionAr: 'عدد الوحدات المشتراة',
        descriptionEn: 'Purchased quantity',
        aliases: ['quantity', 'الكمية', 'كمية_الشراء', 'كمية الشراء', 'qty'],
      },
      {
        key: 'unit_cost',
        labelAr: 'سعر شراء الوحدة',
        labelEn: 'Unit Cost',
        type: 'number',
        required: true,
        example: 42.0,
        descriptionAr: 'تكلفة الوحدة الواحدة قبل الضريبة',
        descriptionEn: 'Per-unit purchase cost before VAT',
        aliases: ['unit_cost', 'سعر_الوحدة', 'سعر الوحدة', 'التكلفة', 'cost', 'unit_price'],
      },
      {
        key: 'tax_rate',
        labelAr: 'نسبة الضريبة %',
        labelEn: 'Tax Rate %',
        type: 'number',
        required: false,
        example: 15,
        descriptionAr: 'نسبة ضريبة القيمة المضافة (افتراضياً 15%)',
        descriptionEn: 'VAT percentage',
        aliases: ['tax_rate', 'الضريبة', 'نسبة_الضريبة', 'vat'],
      },
    ],
    sampleRows: [
      { purchase_no: 'PUR-2026-001', date: '2026-08-29', supplier_code: 'SUP-001', warehouse: 'مستودع الرياض الرئيسي', sku: 'RM-BEEF', quantity: 100, unit_cost: 42.0, tax_rate: 15 },
      { purchase_no: 'PUR-2026-001', date: '2026-08-29', supplier_code: 'SUP-001', warehouse: 'مستودع الرياض الرئيسي', sku: 'RM-CHEE', quantity: 200, unit_cost: 0.70, tax_rate: 15 },
      { purchase_no: 'PUR-2026-002', date: '2026-08-29', supplier_code: 'SUP-002', warehouse: 'مستودع الرياض الرئيسي', sku: 'RM-BUN', quantity: 500, unit_cost: 1.10, tax_rate: 15 },
    ],
    instructionsAr: [
      'نموذج Header + Items في ملف واحد: استخدم رقم الفاتورة (Purchase No) لدمج عدة أصناف في فاتورة واحدة.',
      'سيقوم النظام بالتحقق التام من ربط المستودع بالفرع المصرح للمستخدم.',
      'عند نجاح الاستيراد، يتم إنشاء الفاتورة وإضافة الأرصدة إلى المخزون وتحديث متوسط التكلفة آلياً.',
    ],
    instructionsEn: [
      'Multi-line invoices: Rows with identical Purchase No are grouped into one single purchase invoice.',
      'Warehouse authorization and branch isolation are strictly enforced.',
      'Inventory balances and moving average costs update automatically upon commit.',
    ],
  },

  opening_inventory: {
    id: 'opening_inventory',
    titleAr: 'المخزون الافتتاحي وبداية المدة',
    titleEn: 'Opening Stock Balances',
    descriptionAr: 'استيراد أرصدة بداية المدة للأصناف والمواد الخام مع التشغيلات وتواريخ الصلاحية',
    descriptionEn: 'Import initial stock quantities, unit costs, batches, and expiry dates',
    icon: 'Boxes',
    requiredPermission: 'inventory.stock.adjust',
    primaryKeyColumn: 'sku',
    columns: [
      {
        key: 'sku',
        labelAr: 'كود الصنف / المادة الخام (SKU)',
        labelEn: 'Product / Material SKU',
        type: 'string',
        required: true,
        example: 'BUR-001',
        descriptionAr: 'رمز الصنف المسجل في النظام',
        descriptionEn: 'Registered item SKU',
        aliases: ['sku', 'كود_الصنف', 'كود الصنف', 'كود_المنتج', 'رمز_المادة', 'product_sku'],
      },
      {
        key: 'warehouse',
        labelAr: 'المستودع',
        labelEn: 'Warehouse',
        type: 'string',
        required: true,
        example: 'المستودع الرئيسي',
        descriptionAr: 'اسم أو كود المستودع (يتم التحقق من صلاحية الفرع تلقائياً)',
        descriptionEn: 'Warehouse name or code (Branch isolated)',
        aliases: ['warehouse', 'المستودع', 'المخزن', 'warehouse_name'],
      },
      {
        key: 'quantity',
        labelAr: 'الكمية الافتتاحية',
        labelEn: 'Opening Quantity',
        type: 'number',
        required: true,
        example: 150.0,
        descriptionAr: 'الرصيد الفعلي الموجود بالمستودع',
        descriptionEn: 'Actual stock quantity in warehouse',
        aliases: ['quantity', 'الكمية', 'الرصيد', 'الرصيد_الافتتاحي', 'opening_stock', 'qty'],
      },
      {
        key: 'unit_cost',
        labelAr: 'تكلفة الوحدة الافتتاحية',
        labelEn: 'Opening Unit Cost',
        type: 'number',
        required: true,
        example: 18.5,
        descriptionAr: 'سعر تقييم المخزون الافتتاحي للوحدة',
        descriptionEn: 'Valuation cost per unit in SAR',
        aliases: ['unit_cost', 'التكلفة', 'سعر_الوحدة', 'تكلفة_الوحدة', 'cost'],
      },
      {
        key: 'batch_number',
        labelAr: 'رقم التشغيلة / الدفعة (Batch)',
        labelEn: 'Batch Number',
        type: 'string',
        required: false,
        example: 'BATCH-2026-08',
        descriptionAr: 'رقم التشغيلة لتتبع دفعات المنتجات والمواد',
        descriptionEn: 'Batch or lot identifier',
        aliases: ['batch', 'batch_number', 'رقم_التشغيلة', 'رقم التشغيلة', 'الدفعة', 'lot_number'],
      },
      {
        key: 'expiry_date',
        labelAr: 'تاريخ الصلاحية',
        labelEn: 'Expiry Date',
        type: 'date',
        required: false,
        example: '2027-02-28',
        descriptionAr: 'تاريخ انتهاء الصلاحية للدفعة (YYYY-MM-DD)',
        descriptionEn: 'Batch expiration date',
        aliases: ['expiry_date', 'تاريخ_الصلاحية', 'تاريخ الصلاحية', 'تاريخ_الانتهاء', 'exp_date'],
      },
    ],
    sampleRows: [
      { sku: 'RM-BEEF', warehouse: 'مستودع الرياض الرئيسي', quantity: 250, unit_cost: 42.0, batch_number: 'LOT-BEEF-08', expiry_date: '2026-09-15' },
      { sku: 'RM-CHEE', warehouse: 'مستودع الرياض الرئيسي', quantity: 500, unit_cost: 0.75, batch_number: 'LOT-CHEE-08', expiry_date: '2026-11-30' },
      { sku: 'DRK-001', warehouse: 'مستودع المشروبات', quantity: 1200, unit_cost: 2.2, batch_number: '', expiry_date: '2027-08-01' },
    ],
    instructionsAr: [
      'الأمان والعزل: لا يحتاج ملف الإكسل لتحديد معرفات حساسة (UUIDs). النظام يطابق اسم المستودع ويتحقق من صلاحيات فرعك.',
      'سيتم تحديث رصيد المخزون وحساب القيمة المخزنية الإجمالية للأصناف والمواد الخام فوراً.',
    ],
    instructionsEn: [
      'Zero sensitive IDs in files: System maps warehouse names securely against current tenant & branch permissions.',
      'Stock levels and total inventory asset valuation update immediately.',
    ],
  },

  production: {
    id: 'production',
    titleAr: 'أوامر الإنتاج والتصنيع',
    titleEn: 'Production Orders',
    descriptionAr: 'استيراد سجلات وأوامر الإنتاج وتخريج التام مع خصم المواد الخام المستهلكة',
    descriptionEn: 'Import completed production orders with automated material consumption',
    icon: 'Factory',
    requiredPermission: 'manufacturing.view',
    primaryKeyColumn: 'production_no',
    columns: [
      {
        key: 'production_no',
        labelAr: 'رقم أمر الإنتاج',
        labelEn: 'Production No',
        type: 'string',
        required: true,
        example: 'PROD-2026-001',
        descriptionAr: 'الرمز الفريد لأمر الإنتاج',
        descriptionEn: 'Unique production order code',
        aliases: ['production_no', 'رقم_الامر', 'رقم_الانتاج', 'order_no'],
      },
      {
        key: 'date',
        labelAr: 'تاريخ الإنتاج',
        labelEn: 'Production Date',
        type: 'date',
        required: true,
        example: '2026-08-29',
        descriptionAr: 'تاريخ تنفيذ عملية الإنتاج',
        descriptionEn: 'Production execution date',
        aliases: ['date', 'التاريخ', 'تاريخ_الانتاج', 'تاريخ الإنتاج'],
      },
      {
        key: 'warehouse',
        labelAr: 'مستودع الإنتاج والمواد',
        labelEn: 'Warehouse',
        type: 'string',
        required: true,
        example: 'مستودع المطبخ المركزي',
        descriptionAr: 'المستودع الذي يتم السحب منه والإيداع فيه',
        descriptionEn: 'Source/Destination production warehouse',
        aliases: ['warehouse', 'المستودع', 'المخزن', 'warehouse_name'],
      },
      {
        key: 'product_sku',
        labelAr: 'كود المنتج التام (SKU)',
        labelEn: 'Finished Product SKU',
        type: 'string',
        required: true,
        example: 'BUR-001',
        descriptionAr: 'كود المنتج التام المراد إنتاجه',
        descriptionEn: 'Finished product SKU produced',
        aliases: ['product_sku', 'كود_المنتج', 'كود المنتج', 'المنتج_التام', 'sku'],
      },
      {
        key: 'quantity',
        labelAr: 'الكمية المنتجة',
        labelEn: 'Produced Quantity',
        type: 'number',
        required: true,
        example: 100.0,
        descriptionAr: 'عدد الوحدات تامة الصنع المنتجة',
        descriptionEn: 'Number of finished units produced',
        aliases: ['quantity', 'الكمية', 'الكمية_المنتجة', 'الكمية المنتجة', 'qty'],
      },
    ],
    sampleRows: [
      { production_no: 'PROD-2026-001', date: '2026-08-29', warehouse: 'مستودع المطبخ المركزي', product_sku: 'BUR-001', quantity: 50 },
      { production_no: 'PROD-2026-002', date: '2026-08-29', warehouse: 'مستودع المطبخ المركزي', product_sku: 'BUR-002', quantity: 40 },
    ],
    instructionsAr: [
      'يقوم النظام تلقائياً بالاعتماد على بطاقة وصفة المنتج (Recipe/BOM) لخصم المواد الخام المطلوبة وإضافة المنتج التام للمخزون.',
    ],
    instructionsEn: [
      'System leverages configured product recipes to automatically deplete ingredients and credit finished goods.',
    ],
  },

  transfers: {
    id: 'transfers',
    titleAr: 'التحويلات المخزنية بين الفروع والمستودعات',
    titleEn: 'Stock Warehouse Transfers',
    descriptionAr: 'استيراد وتصدير حركات المناقلة بين المستودعات والفروع',
    descriptionEn: 'Import and export stock transfer vouchers between authorized warehouses',
    icon: 'ArrowLeftRight',
    requiredPermission: 'inventory.transfers.manage',
    primaryKeyColumn: 'transfer_no',
    columns: [
      {
        key: 'transfer_no',
        labelAr: 'رقم المناقلة',
        labelEn: 'Transfer No',
        type: 'string',
        required: true,
        example: 'TR-2026-001',
        descriptionAr: 'رقم سند التحويل',
        descriptionEn: 'Transfer voucher number',
        aliases: ['transfer_no', 'رقم_التحويل', 'رقم التحويل', 'رقم_المناقلة'],
      },
      {
        key: 'date',
        labelAr: 'تاريخ التحويل',
        labelEn: 'Transfer Date',
        type: 'date',
        required: true,
        example: '2026-08-29',
        descriptionAr: 'تاريخ إجراء السند',
        descriptionEn: 'Transfer transaction date',
        aliases: ['date', 'التاريخ', 'تاريخ_التحويل'],
      },
      {
        key: 'from_warehouse',
        labelAr: 'المستودع المصدر (من)',
        labelEn: 'From Warehouse',
        type: 'string',
        required: true,
        example: 'المستودع المركزي',
        descriptionAr: 'اسم المستودع المحول منه',
        descriptionEn: 'Origin warehouse name',
        aliases: ['from_warehouse', 'من_مستودع', 'من مستودع', 'المستودع_المصدر', 'source_warehouse'],
      },
      {
        key: 'to_warehouse',
        labelAr: 'المستودع الوجهة (إلى)',
        labelEn: 'To Warehouse',
        type: 'string',
        required: true,
        example: 'مستودع فرع العليا',
        descriptionAr: 'اسم المستودع المحول إليه',
        descriptionEn: 'Destination warehouse name',
        aliases: ['to_warehouse', 'الى_مستودع', 'إلى مستودع', 'المستودع_الوجهة', 'dest_warehouse'],
      },
      {
        key: 'sku',
        labelAr: 'كود الصنف / المادة (SKU)',
        labelEn: 'Item SKU',
        type: 'string',
        required: true,
        example: 'RM-BEEF',
        descriptionAr: 'رمز الصنف المحول',
        descriptionEn: 'Transferred item SKU',
        aliases: ['sku', 'كود_الصنف', 'كود الصنف', 'product_sku'],
      },
      {
        key: 'quantity',
        labelAr: 'الكمية المحولة',
        labelEn: 'Quantity',
        type: 'number',
        required: true,
        example: 30.0,
        descriptionAr: 'عدد الوحدات المحولة',
        descriptionEn: 'Transferred unit count',
        aliases: ['quantity', 'الكمية', 'كمية_التحويل', 'qty'],
      },
      {
        key: 'notes',
        labelAr: 'ملاحظات',
        labelEn: 'Notes',
        type: 'string',
        required: false,
        example: 'تحويل لتعويض نقص المخزون الأسبوعي',
        descriptionAr: 'بيان أو سبب التحويل',
        descriptionEn: 'Transfer notes or reason',
        aliases: ['notes', 'ملاحظات', 'البيان'],
      },
    ],
    sampleRows: [
      { transfer_no: 'TR-2026-001', date: '2026-08-29', from_warehouse: 'المستودع المركزي', to_warehouse: 'مستودع فرع العليا', sku: 'RM-BEEF', quantity: 50, notes: 'تغذية الفرع' },
      { transfer_no: 'TR-2026-001', date: '2026-08-29', from_warehouse: 'المستودع المركزي', to_warehouse: 'مستودع فرع العليا', sku: 'RM-CHEE', quantity: 100, notes: 'تغذية الفرع' },
    ],
    instructionsAr: [
      'يتم التحقق من توفر رصيد كافٍ في المستودع المصدر.',
      'يمنع النظام التحويل من أو إلى مستودعات لا يملك المستخدم صلاحية عليها.',
    ],
    instructionsEn: [
      'Sufficient stock availability in the source warehouse is pre-validated.',
      'Warehouse authorization barriers apply to prevent unauthorized movement.',
    ],
  },

  expenses: {
    id: 'expenses',
    titleAr: 'المصروفات التشغيلية والبنود',
    titleEn: 'Expenses & Overhead',
    descriptionAr: 'استيراد المصروفات والفواتير النثرية والتشغيلية وربطها بمراكز التكلفة',
    descriptionEn: 'Import operational expenses, petty cash vouchers and cost centers',
    icon: 'Receipt',
    requiredPermission: 'accounting.view',
    primaryKeyColumn: 'expense_no',
    columns: [
      {
        key: 'expense_no',
        labelAr: 'رقم سند الصرف / الفاتورة',
        labelEn: 'Expense / Voucher No',
        type: 'string',
        required: true,
        example: 'EXP-2026-001',
        descriptionAr: 'رقم السند أو الفاتورة الضريبية',
        descriptionEn: 'Expense voucher identifier',
        aliases: ['expense_no', 'رقم_السند', 'رقم السند', 'رقم_المصروف', 'voucher_no'],
      },
      {
        key: 'category',
        labelAr: 'بند المصروف / التصنيف',
        labelEn: 'Expense Category',
        type: 'string',
        required: true,
        example: 'إيجار وصيانة',
        descriptionAr: 'بند المصروف (كهرباء، ماء، صيانة، نظافة، وقود)',
        descriptionEn: 'Expense classification',
        aliases: ['category', 'البند', 'بند_المصروف', 'بند المصروف', 'التصنيف'],
      },
      {
        key: 'amount',
        labelAr: 'المبلغ (شامل الضريبة)',
        labelEn: 'Amount (Gross)',
        type: 'number',
        required: true,
        example: 1500.0,
        descriptionAr: 'قيمة المصروف بالريال السعودي',
        descriptionEn: 'Total expenditure in SAR',
        aliases: ['amount', 'المبلغ', 'القيمة', 'total_amount'],
      },
      {
        key: 'tax_amount',
        labelAr: 'مبلغ الضريبة',
        labelEn: 'Tax Amount',
        type: 'number',
        required: false,
        example: 195.65,
        descriptionAr: 'ضريبة القيمة المضافة المستردة إن وجدت',
        descriptionEn: 'VAT portion if applicable',
        aliases: ['tax_amount', 'الضريبة', 'مبلغ_الضريبة', 'vat_amount'],
      },
      {
        key: 'date',
        labelAr: 'تاريخ الصرف',
        labelEn: 'Expense Date',
        type: 'date',
        required: true,
        example: '2026-08-29',
        descriptionAr: 'تاريخ دفع المصروف',
        descriptionEn: 'Payment date',
        aliases: ['date', 'التاريخ', 'تاريخ_الصرف'],
      },
      {
        key: 'branch',
        labelAr: 'الفرع / مركز التكلفة',
        labelEn: 'Branch / Cost Center',
        type: 'string',
        required: false,
        example: 'الفرع الرئيسي',
        descriptionAr: 'الفرع التابع له المصروف (يُعزل حسب صلاحياتك)',
        descriptionEn: 'Branch cost center',
        aliases: ['branch', 'الفرع', 'اسم_الفرع', 'branch_name'],
      },
      {
        key: 'payment_method',
        labelAr: 'طريقة الدفع (كاش/شبكة/تحويل)',
        labelEn: 'Payment Method',
        type: 'string',
        required: false,
        example: 'شبكة مدى',
        descriptionAr: 'طريقة السداد (نقداً، بنك، عهدة)',
        descriptionEn: 'Payment channel (Cash, Bank, Card)',
        aliases: ['payment_method', 'طريقة_الدفع', 'طريقة الدفع', 'الدفع'],
      },
      {
        key: 'description',
        labelAr: 'البيان / الشرح',
        labelEn: 'Description',
        type: 'string',
        required: false,
        example: 'سداد فاتورة صيانة ماكينة القهوة والفلاتر',
        descriptionAr: 'تفاصيل المصروف للمراجعة المحاسبية',
        descriptionEn: 'Expense memo or narrative',
        aliases: ['description', 'البيان', 'الوصف', 'ملاحظات', 'memo'],
      },
    ],
    sampleRows: [
      { expense_no: 'EXP-2026-001', category: 'صيانة ومعدات', amount: 850.0, tax_amount: 110.87, date: '2026-08-29', branch: 'الفرع الرئيسي', payment_method: 'شبكة', description: 'صيانة دورية للأفران' },
      { expense_no: 'EXP-2026-002', category: 'ضيافة ونظافة', amount: 320.0, tax_amount: 41.74, date: '2026-08-29', branch: 'فرع العليا', payment_method: 'نقدي', description: 'أدوات نظافة للمطبخ' },
    ],
    instructionsAr: ['تأكد من إدخال المبلغ الإجمالي وقيمة الضريبة إن وجدت.', 'سيتم إدراج المصروف مباشرة في قائمة الدخل والتقارير المالية.'],
    instructionsEn: ['Enter amounts accurately.', 'Expenses post to general ledger and income statements.'],
  },

  users: {
    id: 'users',
    titleAr: 'المستخدمون والموظفون',
    titleEn: 'Users & Staff Accounts',
    descriptionAr: 'استيراد حسابات الكاشيرات والمشرفين وربطهم بالأدوار والفروع',
    descriptionEn: 'Import employee logins, assign RBAC roles and authorized branch affiliations',
    icon: 'UserCheck',
    requiredPermission: 'admin.users.manage',
    primaryKeyColumn: 'username',
    columns: [
      {
        key: 'username',
        labelAr: 'اسم المستخدم للـ POS (أو رمز PIN)',
        labelEn: 'Username / POS Code',
        type: 'string',
        required: true,
        example: 'cashier_ali',
        descriptionAr: 'اسم المستخدم الفريد لتسجيل الدخول السريع',
        descriptionEn: 'Unique username or quick POS login code',
        aliases: ['username', 'اسم_المستخدم', 'اسم المستخدم', 'كود_الموظف', 'user'],
      },
      {
        key: 'full_name',
        labelAr: 'الاسم الكامل',
        labelEn: 'Full Name',
        type: 'string',
        required: true,
        example: 'علي بن أحمد القحطاني',
        descriptionAr: 'الاسم الثلاثي للموظف',
        descriptionEn: 'Employee legal full name',
        aliases: ['full_name', 'الاسم_الكامل', 'الاسم الكامل', 'الاسم', 'name'],
      },
      {
        key: 'email',
        labelAr: 'البريد الإلكتروني',
        labelEn: 'Email',
        type: 'string',
        required: false,
        example: 'ali.cashier@premier.sa',
        descriptionAr: 'البريد لتسجيل الدخول واستلام الإشعارات',
        descriptionEn: 'Email address',
        aliases: ['email', 'البريد', 'الايميل', 'البريد_الالكتروني'],
      },
      {
        key: 'role',
        labelAr: 'الدور الوظيفي (Role)',
        labelEn: 'Role',
        type: 'string',
        required: true,
        example: 'cashier',
        descriptionAr: 'الدور (super_admin, pos_admin, branch_manager, cashier, kitchen, accountant, inventory_manager)',
        descriptionEn: 'RBAC Role (cashier, branch_manager, accountant, etc.)',
        aliases: ['role', 'الدور', 'الصلاحية', 'الدور_الوظيفي', 'الوظيفة'],
      },
      {
        key: 'branch',
        labelAr: 'الفرع المخصص',
        labelEn: 'Branch',
        type: 'string',
        required: false,
        example: 'الفرع الرئيسي',
        descriptionAr: 'الفرع الذي سيعمل به المستخدم',
        descriptionEn: 'Assigned branch',
        aliases: ['branch', 'الفرع', 'اسم_الفرع', 'branch_name'],
      },
      {
        key: 'phone',
        labelAr: 'رقم الجوال',
        labelEn: 'Phone Number',
        type: 'string',
        required: false,
        example: '0566112233',
        descriptionAr: 'رقم هاتف الموظف',
        descriptionEn: 'Phone number',
        aliases: ['phone', 'الجوال', 'الهاتف', 'رقم_الجوال'],
      },
      {
        key: 'pin_code',
        labelAr: 'رمز الدخول السريع (PIN 4-6 أرقام)',
        labelEn: 'Quick PIN Code',
        type: 'string',
        required: false,
        example: '1234',
        descriptionAr: 'رمز PIN للدخول السريع لشاشات الكاشير ونقاط البيع',
        descriptionEn: '4-6 digit numeric pin for instant POS login',
        aliases: ['pin', 'pin_code', 'رمز_الدخول', 'رمز الدخول', 'الرمز السري'],
      },
      {
        key: 'is_active',
        labelAr: 'نشط',
        labelEn: 'Active',
        type: 'boolean',
        required: false,
        example: true,
        descriptionAr: 'حالة الحساب',
        descriptionEn: 'Active status',
        aliases: ['active', 'is_active', 'نشط'],
      },
    ],
    sampleRows: [
      { username: 'cashier_ali', full_name: 'علي أحمد القحطاني', email: 'ali@premier.sa', role: 'cashier', branch: 'الفرع الرئيسي', phone: '0555112233', pin_code: '1234', is_active: true },
      { username: 'mgr_khalid', full_name: 'خالد سعيد الدوسري', email: 'khalid@premier.sa', role: 'branch_manager', branch: 'فرع العليا', phone: '0555998877', pin_code: '5678', is_active: true },
    ],
    instructionsAr: [
      'الأدوار المتاحة: cashier (كاشير)، branch_manager (مدير فرع)، kitchen (شاشة مطبخ)، accountant (محاسب)، inventory_manager (مسؤول مستودع).',
      'يمنع إعطاء دور super_admin للمستخدمين العاديين عبر الاستيراد لحماية أمن النظام.',
    ],
    instructionsEn: [
      'Available roles: cashier, branch_manager, kitchen, accountant, inventory_manager.',
      'Super Admin creation is restricted via bulk imports for tenant security compliance.',
    ],
  },
};
